pipeline {
    agent any

    tools {
        terraform 'terraform-1.9.0'
    }

    stages {
        stage('Terraform Init') {
            steps {
                  withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                dir('terraform-04') {
                    sh 'terraform init -input=false'
                }
            }
        }
        }

        stage('Terraform Plan') {
            steps {
                  withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                dir('terraform-04') {
                    sh 'terraform plan -out=tfplan -input=false'
                }
            }
        }
        }

        stage('Approval for Apply') {
            steps {
                input message: "Do you want to apply this Terraform plan?", ok: "Apply"
            }
        }

        stage('Terraform Apply') {
            steps {
                  withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                dir('terraform-04') {
                    sh 'terraform apply -input=false tfplan'
                }
            }
        }
    }
    }

    post {
        always {
            archiveArtifacts artifacts: 'terraform-02/tfplan', allowEmptyArchive: true
            cleanWs()
        }
    }
}
